"""Централизованные статусы и предупреждения инвентаризации."""

from enum import StrEnum


class StatusCode(StrEnum):
    """Допустимые статусы записей, ошибок и предупреждений блока 1."""

    OK = "OK"
    WARNING = "WARNING"
    UNREADABLE_FILE = "UNREADABLE_FILE"
    BROKEN_ARCHIVE = "BROKEN_ARCHIVE"
    UNSAFE_ARCHIVE_PATH = "UNSAFE_ARCHIVE_PATH"
    SUSPICIOUS_COMPRESSION_RATIO = "SUSPICIOUS_COMPRESSION_RATIO"
    VERY_LARGE_ARCHIVE_ENTRY = "VERY_LARGE_ARCHIVE_ENTRY"
    POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"
    ZIP_FILENAME_ENCODING_RECOVERED = "ZIP_FILENAME_ENCODING_RECOVERED"
    SOURCE_FILE_NOT_FOUND = "SOURCE_FILE_NOT_FOUND"
    ARCHIVE_NOT_FOUND = "ARCHIVE_NOT_FOUND"
    ARCHIVE_ENTRY_NOT_FOUND = "ARCHIVE_ENTRY_NOT_FOUND"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    ARCHIVE_ENTRY_TOO_LARGE = "ARCHIVE_ENTRY_TOO_LARGE"
    CRC_MISMATCH = "CRC_MISMATCH"
    UNSUPPORTED_EXCEL_FORMAT = "UNSUPPORTED_EXCEL_FORMAT"
    INVALID_XLSX_CONTAINER = "INVALID_XLSX_CONTAINER"
    MATERIALIZATION_FAILED = "MATERIALIZATION_FAILED"
    WORKSPACE_CREATION_FAILED = "WORKSPACE_CREATION_FAILED"
    CLEANUP_FAILED = "CLEANUP_FAILED"
    FILE_METADATA_CHANGED = "FILE_METADATA_CHANGED"
    SYMLINK_NOT_ALLOWED = "SYMLINK_NOT_ALLOWED"
    WORKBOOK_OPEN_FAILED = "WORKBOOK_OPEN_FAILED"
    WORKBOOK_SESSION_CLOSED = "WORKBOOK_SESSION_CLOSED"
    WORKBOOK_VIEW_MISMATCH = "WORKBOOK_VIEW_MISMATCH"
    SHEET_NOT_FOUND = "SHEET_NOT_FOUND"
    INVALID_CELL_COORDINATE = "INVALID_CELL_COORDINATE"
    FORMULA_WITH_CACHED_VALUE = "FORMULA_WITH_CACHED_VALUE"
    FORMULA_WITHOUT_CACHED_VALUE = "FORMULA_WITHOUT_CACHED_VALUE"
    REAL_EXCEL_ERROR = "REAL_EXCEL_ERROR"
    FORMULA_VIEW_MISMATCH = "FORMULA_VIEW_MISMATCH"
    CELL_READ_FAILED = "CELL_READ_FAILED"
    JSON_WRITE_FAILED = "JSON_WRITE_FAILED"
    INVALID_ARGUMENTS = "INVALID_ARGUMENTS"


class IndexStatus(StrEnum):
    """Статусы извлечения индекса документа."""

    OK = "OK"
    EMPTY_INPUT = "EMPTY_INPUT"
    INDEX_NOT_FOUND = "INDEX_NOT_FOUND"
    MULTIPLE_INDEX_CANDIDATES = "MULTIPLE_INDEX_CANDIDATES"
    INVALID_INPUT_TYPE = "INVALID_INPUT_TYPE"
    LOW_CONFIDENCE_INDEX = "LOW_CONFIDENCE_INDEX"
    INDEX_NOT_PROCESSED = "INDEX_NOT_PROCESSED"


class IndexWarning(StrEnum):
    """Предупреждения извлечения индекса документа."""

    YEAR_LIKE_MAIN_INDEX = "YEAR_LIKE_MAIN_INDEX"
    DUPLICATE_INDEX_OCCURRENCES = "DUPLICATE_INDEX_OCCURRENCES"
    INDEX_CONFIRMED_BY_PARENT_PATH = "INDEX_CONFIRMED_BY_PARENT_PATH"
    TEMPORARY_FILE_SKIPPED = "TEMPORARY_FILE_SKIPPED"


class PeriodExtractionStatus(StrEnum):
    OK = "OK"
    PERIOD_NOT_FOUND = "PERIOD_NOT_FOUND"
    MULTIPLE_PERIOD_CANDIDATES = "MULTIPLE_PERIOD_CANDIDATES"
    INVALID_PERIOD = "INVALID_PERIOD"
    LOW_CONFIDENCE_PERIOD = "LOW_CONFIDENCE_PERIOD"
    PERIOD_NOT_PROCESSED = "PERIOD_NOT_PROCESSED"


class RevisionExtractionStatus(StrEnum):
    OK = "OK"
    REVISION_NOT_FOUND = "REVISION_NOT_FOUND"
    MULTIPLE_REVISION_CANDIDATES = "MULTIPLE_REVISION_CANDIDATES"
    CONFLICTING_VERSION_MARKERS = "CONFLICTING_VERSION_MARKERS"
    REVISION_NOT_PROCESSED = "REVISION_NOT_PROCESSED"


class SourceSelectionStatus(StrEnum):
    OK = "OK"
    SOURCE_NOT_FOUND = "SOURCE_NOT_FOUND"
    NO_ALLOWED_DOCUMENT_TYPES = "NO_ALLOWED_DOCUMENT_TYPES"
    INDEX_NOT_AVAILABLE = "INDEX_NOT_AVAILABLE"
    PERIOD_NOT_AVAILABLE = "PERIOD_NOT_AVAILABLE"
    MULTIPLE_TOP_CANDIDATES = "MULTIPLE_TOP_CANDIDATES"
    ONLY_LOW_CONFIDENCE_CANDIDATES = "ONLY_LOW_CONFIDENCE_CANDIDATES"
    ALL_CANDIDATES_REJECTED = "ALL_CANDIDATES_REJECTED"


class MetadataWarning(StrEnum):
    PERIOD_DERIVED_FROM_FULL_DATE = "PERIOD_DERIVED_FROM_FULL_DATE"
    PERIOD_CONFIRMED_BY_PARENT_PATH = "PERIOD_CONFIRMED_BY_PARENT_PATH"
    INDEX_CONFIRMED_BY_PARENT_PATH = "INDEX_CONFIRMED_BY_PARENT_PATH"
    CONFLICTING_VERSION_MARKERS = "CONFLICTING_VERSION_MARKERS"
