"""Централизованные статусы и предупреждения инвентаризации."""

from enum import StrEnum


class StatusCode(StrEnum):
    """Допустимые статусы записей, ошибок и предупреждений блока 1."""

    OK = "OK"
    WARNING = "WARNING"
    UNREADABLE_FILE = "UNREADABLE_FILE"
    BROKEN_ARCHIVE = "BROKEN_ARCHIVE"
    UNSAFE_ARCHIVE_PATH = "UNSAFE_ARCHIVE_PATH"
    SUSPICIOUS_COMPRESSION_RATIO = "SUSPICIOUS_COMPRESSION_RATIO"
    VERY_LARGE_ARCHIVE_ENTRY = "VERY_LARGE_ARCHIVE_ENTRY"
    POSSIBLE_DUPLICATE = "POSSIBLE_DUPLICATE"
    ZIP_FILENAME_ENCODING_RECOVERED = "ZIP_FILENAME_ENCODING_RECOVERED"


class IndexStatus(StrEnum):
    """Статусы извлечения индекса документа."""

    OK = "OK"
    EMPTY_INPUT = "EMPTY_INPUT"
    INDEX_NOT_FOUND = "INDEX_NOT_FOUND"
    MULTIPLE_INDEX_CANDIDATES = "MULTIPLE_INDEX_CANDIDATES"
    INVALID_INPUT_TYPE = "INVALID_INPUT_TYPE"
    LOW_CONFIDENCE_INDEX = "LOW_CONFIDENCE_INDEX"
    INDEX_NOT_PROCESSED = "INDEX_NOT_PROCESSED"


class IndexWarning(StrEnum):
    """Предупреждения извлечения индекса документа."""

    YEAR_LIKE_MAIN_INDEX = "YEAR_LIKE_MAIN_INDEX"
    DUPLICATE_INDEX_OCCURRENCES = "DUPLICATE_INDEX_OCCURRENCES"
    INDEX_CONFIRMED_BY_PARENT_PATH = "INDEX_CONFIRMED_BY_PARENT_PATH"
    TEMPORARY_FILE_SKIPPED = "TEMPORARY_FILE_SKIPPED"
