"""Central column alias rules; no fuzzy matching or future adapter logic."""

from report_processor.schema.models import ColumnAliasRule, LogicalColumn, SheetType

_TABULAR = (
    SheetType.KS2,
    SheetType.KS3,
    SheetType.KS6A,
    SheetType.SVVR,
    SheetType.KS2_REGISTRY,
    SheetType.ADDITIONAL_REPORT,
    SheetType.SUBOBJECT_REFERENCE,
    SheetType.VISR,
    SheetType.DRDC,
    SheetType.PROTOCOL,
)
_WORK = (
    SheetType.KS2,
    SheetType.KS6A,
    SheetType.SVVR,
    SheetType.ADDITIONAL_REPORT,
    SheetType.VISR,
    SheetType.DRDC,
)

DEFAULT_COLUMN_ALIASES: tuple[ColumnAliasRule, ...] = (
    ColumnAliasRule(
        LogicalColumn.ROW_NUMBER,
        ("номер п п", "номер по порядку", "порядковый номер"),
        ("номер",),
        ("поряд", "п п"),
        ("позиция",),
        _TABULAR,
        90,
    ),
    ColumnAliasRule(
        LogicalColumn.DOCUMENT_INDEX,
        ("индекс", "индекс документа"),
        ("индекс",),
        ("документ",),
        (),
        _TABULAR,
        85,
    ),
    ColumnAliasRule(
        LogicalColumn.STAGE,
        ("этап", "этап работ", "номер этапа"),
        ("этап",),
        ("работ", "номер"),
        ("наименование",),
        _TABULAR,
        75,
    ),
    ColumnAliasRule(
        LogicalColumn.OBJECT_CODE,
        ("код объекта", "шифр объекта"),
        ("объект",),
        ("код", "шифр"),
        ("подобъект", "наименование"),
        _WORK,
        90,
    ),
    ColumnAliasRule(
        LogicalColumn.OBJECT_NAME,
        ("наименование объекта", "объект"),
        ("объект",),
        ("наименование",),
        ("код", "подобъект"),
        _WORK,
        70,
    ),
    ColumnAliasRule(
        LogicalColumn.SUBOBJECT_CODE,
        ("код подобъекта", "шифр подобъекта"),
        ("подобъект",),
        ("код", "шифр"),
        ("наименование",),
        _WORK,
        90,
    ),
    ColumnAliasRule(
        LogicalColumn.SUBOBJECT_NAME,
        ("наименование подобъекта",),
        ("подобъект", "наименование"),
        (),
        ("код",),
        _WORK,
        85,
    ),
    ColumnAliasRule(
        LogicalColumn.POSITION_CODE,
        ("номер позиции", "позиция", "позиция по расчету договорной цены"),
        ("позиция",),
        ("номер", "договорной", "цены"),
        ("наименование",),
        _WORK,
        88,
    ),
    ColumnAliasRule(
        LogicalColumn.WORK_NAME,
        (
            "наименование работ",
            "наименование работ и затрат",
            "наименование этапа выполнения работ",
            "вид работ",
            "этап работ",
        ),
        ("работ",),
        ("наименование", "этап", "вид", "затрат"),
        ("стоимость", "количество", "код"),
        _WORK,
        100,
    ),
    ColumnAliasRule(
        LogicalColumn.UNIT,
        ("единица измерения", "единица"),
        ("единица",),
        ("измерения",),
        ("цена", "стоимость"),
        _WORK,
        100,
    ),
    ColumnAliasRule(
        LogicalColumn.CONTRACT_QUANTITY,
        ("количество по проекту", "количество по договору", "договорное количество"),
        ("количество",),
        ("проект", "договор", "проектной", "документации"),
        ("отчетный", "начала", "остаток", "месяц", "выполнено"),
        _WORK,
        92,
    ),
    ColumnAliasRule(
        LogicalColumn.CURRENT_PERIOD_QUANTITY,
        (
            "выполнено за отчетный период количество",
            "объем за отчетный период",
            "количество за месяц",
            "текущий период количество",
        ),
        ("количество",),
        ("отчетный", "период", "месяц", "текущий", "выполнено"),
        ("начала", "накоп", "остаток", "договор", "проект"),
        _WORK,
        98,
    ),
    ColumnAliasRule(
        LogicalColumn.CURRENT_PERIOD_QUANTITY,
        ("объем за отчетный период",),
        ("объем", "отчет"),
        ("период",),
        ("начала", "остаток"),
        _WORK,
        97,
    ),
    ColumnAliasRule(
        LogicalColumn.CUMULATIVE_QUANTITY,
        (
            "выполнено с начала строительства количество",
            "накопительное количество",
            "выполнено за весь период строительства количество",
        ),
        ("количество",),
        ("начала", "строительства", "накоп", "весь", "период"),
        ("остаток", "отчетный", "месяц"),
        _WORK,
        98,
    ),
    ColumnAliasRule(
        LogicalColumn.REMAINING_QUANTITY,
        ("остаток количества", "остаток работ по договору количество"),
        ("остаток",),
        ("количество", "работ", "договор"),
        ("стоимость",),
        _WORK,
        96,
    ),
    ColumnAliasRule(
        LogicalColumn.UNIT_PRICE,
        ("цена за единицу", "стоимость за единицу", "единичная стоимость", "расценка"),
        ("единицу",),
        ("цена", "стоимость", "расценка"),
        ("общая", "всего", "период", "начала"),
        _WORK,
        100,
    ),
    ColumnAliasRule(
        LogicalColumn.UNIT_PRICE,
        ("расценка",),
        ("расценка",),
        (),
        ("общая",),
        _WORK,
        100,
    ),
    ColumnAliasRule(
        LogicalColumn.CURRENT_PERIOD_COST,
        (
            "выполнено за отчетный период стоимость",
            "стоимость за месяц",
            "текущая стоимость",
        ),
        ("стоимость",),
        ("отчетный", "период", "месяц", "текущ", "выполнено"),
        ("единицу", "начала", "накоп", "общая", "лимит"),
        _WORK,
        98,
    ),
    ColumnAliasRule(
        LogicalColumn.CUMULATIVE_COST,
        (
            "выполнено с начала строительства стоимость",
            "накопительная стоимость",
            "стоимость за весь период строительства",
        ),
        ("стоимость",),
        ("начала", "строительства", "накоп", "весь", "период"),
        ("единицу", "отчетный", "месяц", "лимит"),
        _WORK,
        98,
    ),
    ColumnAliasRule(
        LogicalColumn.TOTAL_COST,
        ("общая стоимость", "стоимость всего", "стоимость работ всего"),
        ("стоимость",),
        ("общая", "всего", "работ"),
        ("единицу", "отчетный", "начала", "лимит", "за"),
        _WORK,
        94,
    ),
    ColumnAliasRule(
        LogicalColumn.LIMIT_VALUE,
        ("лимит", "предельное значение", "контрольная стоимость"),
        ("лимит",),
        ("предельное", "контрольная", "стоимость"),
        ("общая", "единицу"),
        (SheetType.ADDITIONAL_REPORT, SheetType.DRDC),
        100,
    ),
    ColumnAliasRule(
        LogicalColumn.BASIS_CODE,
        ("обоснование", "код обоснования"),
        ("обоснование",),
        ("код",),
        (),
        _WORK,
        80,
    ),
    ColumnAliasRule(
        LogicalColumn.DRAWING_CODE,
        ("шифр чертежа", "код чертежа"),
        ("чертеж",),
        ("шифр", "код"),
        (),
        _WORK,
        85,
    ),
    ColumnAliasRule(
        LogicalColumn.COST_TYPE_CODE,
        ("код вида затрат", "вид затрат"),
        ("затрат",),
        ("код", "вид"),
        ("наименование",),
        _WORK,
        88,
    ),
)
