"""Central status and warning codes for schema detection."""

from enum import StrEnum


class SchemaStatus(StrEnum):
    OK = "OK"
    UNKNOWN_SHEET_TYPE = "UNKNOWN_SHEET_TYPE"
    AMBIGUOUS_SHEET_TYPE = "AMBIGUOUS_SHEET_TYPE"
    LOW_CONFIDENCE_SHEET_TYPE = "LOW_CONFIDENCE_SHEET_TYPE"
    SHEET_SCAN_FAILED = "SHEET_SCAN_FAILED"
    HEADER_NOT_FOUND = "HEADER_NOT_FOUND"
    AMBIGUOUS_HEADER = "AMBIGUOUS_HEADER"
    COLUMN_NOT_FOUND = "COLUMN_NOT_FOUND"
    AMBIGUOUS_COLUMN = "AMBIGUOUS_COLUMN"
    COLUMNS_NOT_RESOLVED = "COLUMNS_NOT_RESOLVED"
    MISSING_REQUIRED_COLUMNS = "MISSING_REQUIRED_COLUMNS"
    LOW_CONFIDENCE_SCHEMA = "LOW_CONFIDENCE_SCHEMA"
    SHEET_SCAN_LIMIT_REACHED = "SHEET_SCAN_LIMIT_REACHED"
    SCHEMA_DETECTION_FAILED = "SCHEMA_DETECTION_FAILED"
    WARNING = "WARNING"


class SchemaWarning(StrEnum):
    SCAN_CELL_LIMIT_REACHED = "SCAN_CELL_LIMIT_REACHED"
    SCAN_STOPPED_AFTER_EMPTY_ROWS = "SCAN_STOPPED_AFTER_EMPTY_ROWS"
    MERGED_RANGES_STREAMED_FROM_XML = "MERGED_RANGES_STREAMED_FROM_XML"
    MULTIPLE_SHEETS_OF_SAME_TYPE = "MULTIPLE_SHEETS_OF_SAME_TYPE"
    MISSING_REQUIRED_COLUMNS = "MISSING_REQUIRED_COLUMNS"
    AMBIGUOUS_COLUMNS = "AMBIGUOUS_COLUMNS"
    TABLE_COLUMN_GAPS = "TABLE_COLUMN_GAPS"
    DATA_START_NOT_FOUND = "DATA_START_NOT_FOUND"
    MANUAL_OVERRIDE_APPLIED = "MANUAL_OVERRIDE_APPLIED"
    LOW_CONFIDENCE = "LOW_CONFIDENCE"
